/* Generated by Together */



package com.viewscenes.device.framework;



/**

 * <pre>

 * 该类将作为与设备通信的消息的载体

 * 消息发送者调用getMessage获得消息，调用getTimedout获得超时时间

 * 每一下行xml消息应对应一个实现类，各实现类可以增加设置具体信息的方法

 * </pre>

 * @version 1.0

 */

public interface IMessageCommand {

  /**

   * 当向设备或其他可以接收消息的对象发送消息前，调用此方法，获得消息

   * @return 返回一个IMessage对象

   * @see IMessage

   */

  IMessage getMessage();



  /**

   * 对每条消息，可以设置单独的超时时间

   * @return 该消息的超时时间，单位为秒

   */

  int getTimedout();

}
