/* Generated by Together */



package com.viewscenes.device.framework;



import com.viewscenes.device.exception.*;



/**

 * <pre>

 * 该类将作为与设备通信的消息的载体

 * 消息接收者调用setMessage设置消息

 * 每一上行xml消息应对应一个实现类，各实现类可以增加获得具体信息的方法

 * </pre>

 * @version 1.0

 */

public interface IMessageResponse {

  /**

   * 设置消息

   * @param msg 从设备或其他来源获得的消息

   * @preconditions msg != null

   * @throws DeviceReportException 当返回带有错误信息的消息时抛出异常

   * @see IMessage

   */

  void setMessage(IMessage msg) throws DeviceReportException;

}
