/* Generated by Together */



package com.viewscenes.device.util;



import java.util.*;

import org.jdom.*;

/**

 * <pre>

 * 对设备支持的消息类型的抽象，具有版本，类型文本等属性

 * 该类具有不变性，且数量有限，可在系统中共享

 * 系统初始化时，读取数据源构造系统中所有消息类型，放入池中共享使用

 * </pre>

 * @pattern flyweight

 * @version 1.0

 */

public final class InnerMsgType {

  private InnerMsgType(String version, String type) {

    this.version = version;

    this.type = type;

  }



  public static InnerMsgType instance(String name) {

    Object o = types.get(name);

    return (InnerMsgType) o;

  }



  public String getVersion() {

    return version;

  }



  public String getType() {

    return type;

  }



  private String version;

  private String type;

  private static Map types;

  static {

    List children = MsgUtil.getConfigItem("msgtype").getChildren();

    types = new HashMap(children.size());

    for (Iterator it = children.iterator(); it.hasNext(); ) {

      Element child = (Element) it.next();

      types.put(child.getName(),

                new InnerMsgType(child.getAttributeValue("version"),

                                 child.getAttributeValue("type")));

    }

  }

}

