/* Generated by Together */

package com.viewscenes.device.exception;

/**
 * 
 * 消息处理过程中的异常
 * 
 * @version 1.0
 */

public class DeviceProcessException

extends DeviceException {

	public DeviceProcessException(String desc) {

		super(desc);

	}

	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "原因：消息处理过程中出现异常|详细:" + super.getMessage();
	}
}
