/* Generated by Together */

package com.viewscenes.device.exception;

/**
 * 
 * 当设备返回的消息的return元素的value的值不为0，即失败时返回
 * 
 * @version 1.0
 */

public class DeviceReportException

extends DeviceException {

	public DeviceReportException(String code, String desc) {

		super(desc);

		this.code = code;

	}

	public String code() {

		return this.code;

	}

	private String code;

	/**
	 * 根据V8接口设定返回异常信息
	 */
	@Override
	public String getMessage() {
		String msg = "";
		// TODO Auto-generated method stub
		if (code.equals("1")) {
			msg = "原因：目的地址错误|详细:" + super.getMessage();
		} else if (code.equals("2")) {
			msg = "原因：优先级低|详细:" + super.getMessage();
		} else if (code.equals("3")) {
			msg = "原因：版本错误|详细:" + super.getMessage();
		} else if (code.equals("4")) {
			msg = "原因：消息ID错误|详细:" + super.getMessage();
		} else if (code.equals("5")) {
			msg = "原因：消息类型错误|详细:" + super.getMessage();
		} else if (code.equals("6")) {
			msg = "原因：源地址错误|详细:" + super.getMessage();
		} else if (code.equals("7")) {
			msg = "原因：消息格式错误|详细:" + super.getMessage();
		} else if (code.equals("9")) {
			msg = "原因：未知错误|详细:" + super.getMessage();
		} else if (code.equals("10")) {
			msg = "原因：设备内部错误|详细:" + super.getMessage();
		} else if (code.equals("101")) {
			msg = "原因：任务已存在|详细:" + super.getMessage();
		} else if (code.equals("102")) {
			msg = "原因：任务不存在|详细:" + super.getMessage();
		} else {
			msg = "原因：设备返回失败|详细:" + super.getMessage();
		}

		return msg;
	}

}
