/* Generated by Together */

package com.viewscenes.device.exception;

import com.viewscenes.pub.exception.*;

import com.viewscenes.util.LogTool;

/**
 * 
 * 本模块异常基类
 * 
 * @version 1.0
 */

public class DeviceException

extends AppException {

	public DeviceException(String desc) {

		super(desc);

	}

	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "原因：设备异常错误|详细:" + super.getMessage();
	}
}
