/* Generated by Together */

package com.viewscenes.device.exception;

/**
 * 
 * 设备不存在，即客户传入了错误的设备编码（目前指没在配置文件中正确配置的设备）
 * 
 * @version 1.0
 */

public class DeviceNotExistException

extends DeviceException {

	public DeviceNotExistException(String desc) {

		super(desc);

	}

	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "原因：设备编码错误,设备不存在|详细:" + super.getMessage();
	}
}
