/* Generated by Together */

package com.viewscenes.device.exception;

/**
 * 
 * 等待消息返回超时
 * 
 * @version 1.0
 */

public class DeviceTimedOutException

extends DeviceException {

	public DeviceTimedOutException(String desc) {

		super(desc);

	}

	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "原因：等待消息返回超时|详细:"+super.getMessage();
	}

}
