/* Generated by Together */

package com.viewscenes.device.exception;

/**
 * 
 * 消息通不过验证时抛出该异常
 * 
 * @version 1.0
 */

public class DeviceFilterException

extends DeviceException {

	public DeviceFilterException(String desc) {

		super(desc);

	}

	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "原因：发送消息验证失败|详细:" + super.getMessage();
	}
}
